In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.linspace(0.0,5.0,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(5)

array([0.75507295, 0.07397285, 0.24897641, 0.99242946, 0.56789206])

In [21]:
np.random.rand(5,5)

array([[0.83364464, 0.9880414 , 0.50306598, 0.47006284, 0.54506292],
       [0.38288873, 0.26738574, 0.38824206, 0.77259133, 0.75182561],
       [0.6959195 , 0.01777894, 0.99787606, 0.53015005, 0.93045232],
       [0.78362141, 0.05958485, 0.408952  , 0.65000671, 0.13901731],
       [0.21184719, 0.27908259, 0.1352594 , 0.56733512, 0.07997406]])

In [22]:
np.random.randn(2)

array([-0.54498539, -1.13667241])

In [23]:
np.random.randn(4,4)

array([[ 0.38468948, -1.70523498, -1.36612569, -0.02004628],
       [ 0.17456695,  0.19117206, -0.81830507,  1.5856215 ],
       [-0.13762647, -0.32976314, -0.5979449 , -0.47110078],
       [ 1.48221218, -2.11297824,  0.90000823,  1.293224  ]])

In [25]:
np.random.randint(1,100) #100 is not included

54

In [26]:
np.random.randint(1,100,10)

array([ 1, 57, 45, 17, 23,  9, 11, 45, 23, 15])

In [27]:
arr=np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr=np.random.randint(0,50,10)

In [33]:
ranarr

array([11, 46, 25, 18, 48, 27, 30, 23, 10, 30])

In [34]:
#Methods for arrays

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr.max()

48

In [36]:
ranarr.min()

10

In [37]:
ranarr.argmax() # index location

4

In [38]:
ranarr.argmin() # index location

8

In [41]:
arr2=arr.reshape(5,5)

In [43]:
arr2.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [47]:
np.random.randn(5).dtype

dtype('float64')

In [1]:
arr=np.arange(0,11)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[:2]

array([0, 1])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[-1]

10

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5]=1

In [13]:
arr

array([ 1,  1,  1,  1,  1,  5,  6,  7,  8,  9, 10])

In [14]:
arr_slice=arr[:5].copy()

In [18]:
arr_slice[:3]=5

In [19]:
arr_slice

array([5, 5, 5, 1, 1])

In [20]:
arr

array([ 1,  1,  1,  1,  1,  5,  6,  7,  8,  9, 10])

In [27]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[0,0]

5

In [24]:
arr_2d[0]

array([ 5, 10, 15])

In [25]:
arr_2d[1][1]

25

In [28]:
arr_2d[1,1]

25

In [29]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [30]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [31]:
arr_cond=np.arange(1,11)

In [32]:
arr_cond

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
bool_arr=arr_cond<6

In [35]:
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [37]:
arr_cond[bool_arr]

array([1, 2, 3, 4, 5])

In [38]:
arr_cond[arr_cond>5]

array([ 6,  7,  8,  9, 10])

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [6]:
np.max(arr)


10

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
arr/0

d:\Users\MM15493\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
d:\Users\MM15493\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])